module.exports = {
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:import/recommended",
    "plugin:import/typescript",
  ],
  "env": {
    "browser": true,
    "node": true,
  },
  settings: {
    "import/resolver": {
      node: {
        extensions: [".ts"],
        moduleDirectory: ["node_modules", "src"],
      },
    },
  },
  rules: {
    "arrow-spacing": "error",
    "comma-spacing": ["error", { "before": false, "after": true }],
    "consistent-return": "error",
    "eol-last": "error",
    "eqeqeq": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "max-len": ["error", 120],
    "max-lines": ["error", 100],
    "newline-after-var": "error",
    "no-console": "error",
    "no-else-return": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0, "maxBOF": 0 }],
    "no-trailing-spaces": "error",
    "object-shorthand": "error",
    "padded-blocks": ["error", "never"],
    "quotes": ["error", "double"],
    "semi": "error",
    "semi-spacing": "error",
    "space-in-parens": ["error", "never"],

    "import/first": "error",
    "import/newline-after-import": ["error", { "count": 1 }],
    "import/no-cycle": "error",
    "import/order": ["error", {
      "groups": ["external", "index", "sibling", "parent", "internal", "builtin", "object", "type"],
      "alphabetize": { "order": "asc", "caseInsensitive": true },
    }],

    "@typescript-eslint/brace-style": "error",
    "@typescript-eslint/comma-dangle": ["error", "always-multiline"],
    "@typescript-eslint/consistent-type-definitions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/indent": ["error", 2],
    "@typescript-eslint/member-delimiter-style": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-shadow": "error",
    "@typescript-eslint/no-unnecessary-condition": "error",
    "@typescript-eslint/no-unused-expressions": "error",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-use-before-define": "error",
    "@typescript-eslint/object-curly-spacing": ["error", "always"],
    "@typescript-eslint/padding-line-between-statements": [
      "error",
      { "blankLine": "always", "prev": "*", "next": "block-like" },
      { "blankLine": "always", "prev": "block-like", "next": "*" },
      { "blankLine": "always", "prev": "*", "next": "return" },
      { "blankLine": "always", "prev": "*", "next": "export" },
    ],
    "@typescript-eslint/semi": "error",
    "@typescript-eslint/space-infix-ops": "error",
    "@typescript-eslint/type-annotation-spacing": "error",
  },
  parserOptions: {
    project: ["./tsconfig.json"],
  },
};
